import type { UsageGuide } from "./foundations.ts";
import type { LessonDefinition, VisualizationStep, VisualEdge, VisualItem } from "../visualization/types.ts";

export type WeightedGraphLessonId = "weighted-basics" | "dijkstra" | "bellman-ford" | "floyd-warshall" | "prim" | "kruskal" | "union-find";
export type WeightedEdgeInput = { from: string; to: string; weight: number };
export type WeightedGraphInput = { nodes: string[]; edges: WeightedEdgeInput[]; start: string };
export type WeightedGraphMeta = Readonly<{ id: WeightedGraphLessonId; navLabel: string; shortLabel: string; title: string; description: string; concept: string; rule: string; analogy: string; usage: UsageGuide }>;

function validateWeighted(input: WeightedGraphInput, directed: boolean, options: { nonnegative?: boolean; connected?: boolean } = {}) {
  const { nodes, edges, start } = input;
  if (nodes.length < 3 || nodes.length > 7) return { valid: false as const, message: "Use 3 to 7 vertices." };
  if (new Set(nodes).size !== nodes.length || nodes.some((node) => !/^[A-Z0-9]{1,3}$/.test(node))) return { valid: false as const, message: "Use unique 1–3 character vertex labels." };
  if (!nodes.includes(start)) return { valid: false as const, message: "The start vertex must exist." };
  if (!edges.length || edges.length > 14) return { valid: false as const, message: "Use 1 to 14 weighted edges." };
  if (edges.some((edge) => !nodes.includes(edge.from) || !nodes.includes(edge.to) || edge.from === edge.to || !Number.isInteger(edge.weight) || Math.abs(edge.weight) > 50)) return { valid: false as const, message: "Every edge needs two listed vertices and a whole-number weight from −50 to 50." };
  if (options.nonnegative && edges.some((edge) => edge.weight < 0)) return { valid: false as const, message: "Dijkstra requires non-negative edge weights." };
  const keys = edges.map((edge) => directed ? `${edge.from}>${edge.to}` : [edge.from, edge.to].sort().join("-"));
  if (new Set(keys).size !== keys.length) return { valid: false as const, message: "Remove duplicate edges." };
  if (options.connected && !isConnected(input)) return { valid: false as const, message: "A spanning tree requires every vertex to be connected." };
  return { valid: true as const };
}

function edgeId(index: number) { return `weighted-edge-${index}`; }
function adjacency(input: WeightedGraphInput, directed: boolean) {
  const lists = new Map(input.nodes.map((node) => [node, [] as Array<{ node: string; weight: number; edge: string }>]));
  input.edges.forEach((edge, index) => { lists.get(edge.from)!.push({ node: edge.to, weight: edge.weight, edge: edgeId(index) }); if (!directed) lists.get(edge.to)!.push({ node: edge.from, weight: edge.weight, edge: edgeId(index) }); });
  return lists;
}

function isConnected(input: WeightedGraphInput) {
  const lists = adjacency(input, false); const seen = new Set([input.nodes[0]]); const queue = [input.nodes[0]];
  while (queue.length) for (const next of lists.get(queue.shift()!)!) if (!seen.has(next.node)) { seen.add(next.node); queue.push(next.node); }
  return seen.size === input.nodes.length;
}

function nodeItems(nodes: string[], active: string[] = [], completed: string[] = [], entering: string[] = [], labels: Record<string, string> = {}): VisualItem[] {
  return nodes.map((node) => ({ id: `graph-${node}`, value: node, label: labels[node] ?? "VERTEX", state: active.includes(node) ? "active" : entering.includes(node) ? "entering" : completed.includes(node) ? "completed" : "idle" }));
}

function visualEdges(input: WeightedGraphInput, directed: boolean, active: string[] = [], completed: string[] = [], muted: string[] = []): VisualEdge[] {
  return input.edges.map((edge, index) => { const id = edgeId(index); return { id, from: `graph-${edge.from}`, to: `graph-${edge.to}`, label: String(edge.weight), directed, state: active.includes(id) ? "active" : completed.includes(id) ? "completed" : muted.includes(id) ? "muted" : "idle" }; });
}

function weightedFrame(input: WeightedGraphInput, directed: boolean, activeNodes: string[], completedNodes: string[], caption: string, output: Array<string | number> = [], activeEdges: string[] = [], completedEdges: string[] = [], enteringNodes: string[] = [], mutedEdges: string[] = [], labels: Record<string, string> = {}) {
  return { layout: "graph" as const, items: nodeItems(input.nodes, activeNodes, completedNodes, enteringNodes, labels), edges: visualEdges(input, directed, activeEdges, completedEdges, mutedEdges), caption, output };
}

function distanceLabels(nodes: string[], distances: Map<string, number>) { return Object.fromEntries(nodes.map((node) => [node, `DIST ${Number.isFinite(distances.get(node)) ? distances.get(node) : "∞"}`])); }
function distanceOutput(nodes: string[], distances: Map<string, number>) { return nodes.map((node) => `${node}=${Number.isFinite(distances.get(node)) ? distances.get(node) : "∞"}`); }

function dijkstraResult(input: WeightedGraphInput, directed: boolean) {
  const lists = adjacency(input, directed); const distance = new Map(input.nodes.map((node) => [node, Infinity])); const parent = new Map<string, string | null>([[input.start, null]]); const visited = new Set<string>(); distance.set(input.start, 0);
  while (visited.size < input.nodes.length) { const current = input.nodes.filter((node) => !visited.has(node)).reduce<string | null>((best, node) => best === null || distance.get(node)! < distance.get(best)! ? node : best, null); if (current === null || !Number.isFinite(distance.get(current))) break; visited.add(current); for (const next of lists.get(current)!) { const candidate = distance.get(current)! + next.weight; if (candidate < distance.get(next.node)!) { distance.set(next.node, candidate); parent.set(next.node, current); } } }
  return { distance, parent };
}

export const weightedBasicsLesson: LessonDefinition<WeightedGraphInput> = {
  id: "weighted-basics", title: "Weighted graph concepts", category: "data-structure",
  code: ["graph['A'] = [('B', 4), ('C', 2)]", "", "path_cost = sum(edge.weight for edge in path)", "", "candidate = distance[u] + weight", "distance[v] = min(distance[v], candidate)"],
  validate: (input) => validateWeighted(input, false, { nonnegative: true, connected: true }),
  createSteps: (input) => {
    const first = input.edges[0]; const result = dijkstraResult(input, false); const target = input.nodes.at(-1)!; const path: string[] = []; let current: string | null = target; while (current) { path.unshift(current); current = result.parent.get(current) ?? null; } const pathEdges = path.slice(1).map((node, index) => { const from = path[index]; const edgeIndex = input.edges.findIndex((edge) => edge.from === from && edge.to === node || edge.from === node && edge.to === from); return edgeId(edgeIndex); }); const startEdge = input.edges.findIndex((edge) => edge.from === input.start || edge.to === input.start); const neighbor = input.edges[startEdge].from === input.start ? input.edges[startEdge].to : input.edges[startEdge].from;
    return [
      { id: "weighted-0", operation: "read-weights", explanation: "Each edge label stores a cost such as distance, time, money, or risk.", codeLine: 0, frame: weightedFrame(input, false, input.nodes, [], "Numbers on edges are traversal costs") },
      { id: "weighted-1", operation: "inspect-edge", explanation: `Moving across ${first.from} — ${first.to} adds ${first.weight} to the path cost.`, codeLine: 2, frame: weightedFrame(input, false, [first.from, first.to], [], `Edge cost: ${first.weight}`, [first.weight], [edgeId(0)]) },
      { id: "weighted-2", operation: "relax-edge", explanation: `From ${input.start}, edge weight ${input.edges[startEdge].weight} gives ${neighbor} a tentative distance of ${input.edges[startEdge].weight}. This update is called relaxation.`, codeLine: 5, frame: weightedFrame(input, false, [input.start, neighbor], [input.start], `∞ becomes ${input.edges[startEdge].weight}`, [`${input.start}=0`, `${neighbor}=${input.edges[startEdge].weight}`], [edgeId(startEdge)], [], [neighbor], [], { [input.start]: "DIST 0", [neighbor]: `DIST ${input.edges[startEdge].weight}` }) },
      { id: "weighted-3", operation: "compare-paths", explanation: `A cheapest path to ${target} is ${path.join(" → ")} with total cost ${result.distance.get(target)}. Fewer edges do not always mean lower cost.`, codeLine: 2, frame: weightedFrame(input, false, path, [], `Cheapest cost ${input.start} → ${target}: ${result.distance.get(target)}`, path, pathEdges) },
      { id: "weighted-4", operation: "concept-ready", explanation: "Weighted algorithms repeatedly compare complete path costs rather than simply counting edges.", codeLine: 5, frame: weightedFrame(input, false, [], input.nodes, "Weighted graph ready", distanceOutput(input.nodes, result.distance), [], pathEdges, [], [], distanceLabels(input.nodes, result.distance)) },
    ];
  },
};

export const dijkstraLesson: LessonDefinition<WeightedGraphInput> = {
  id: "dijkstra", title: "Dijkstra's algorithm", category: "algorithm",
  code: ["def dijkstra(graph, start):", "    distance = {v: inf for v in graph}", "    distance[start] = 0", "    queue = [(0, start)]", "    while queue:", "        cost, vertex = heappop(queue)", "        if cost != distance[vertex]: continue", "        for neighbor, weight in graph[vertex]:", "            candidate = cost + weight", "            if candidate < distance[neighbor]:", "                distance[neighbor] = candidate", "                heappush(queue, (candidate, neighbor))", "    return distance"],
  validate: (input) => validateWeighted(input, true, { nonnegative: true }),
  createSteps: (input) => {
    const lists = adjacency(input, true); const distance = new Map(input.nodes.map((node) => [node, Infinity])); distance.set(input.start, 0); const settled: string[] = []; const steps: VisualizationStep[] = [{ id: "dijkstra-0", operation: "initialize", explanation: `Set ${input.start} to 0 and every other tentative distance to infinity.`, codeLine: 2, frame: weightedFrame(input, true, [input.start], [], `Priority queue: 0:${input.start}`, distanceOutput(input.nodes, distance), [], [], [input.start], [], distanceLabels(input.nodes, distance)) }]; let sequence = 1;
    while (settled.length < input.nodes.length) { const current = input.nodes.filter((node) => !settled.includes(node)).reduce<string | null>((best, node) => best === null || distance.get(node)! < distance.get(best)! ? node : best, null); if (current === null || !Number.isFinite(distance.get(current))) break; settled.push(current); steps.push({ id: `dijkstra-${sequence++}`, operation: "settle-minimum", explanation: `${current} has the smallest tentative distance, ${distance.get(current)}. Non-negative weights make it safe to finalize.`, codeLine: 5, frame: weightedFrame(input, true, [current], settled.slice(0, -1), `Settle ${current} at distance ${distance.get(current)}`, distanceOutput(input.nodes, distance), [], [], [], [], distanceLabels(input.nodes, distance)) }); for (const next of lists.get(current)!) { if (settled.includes(next.node)) continue; const candidate = distance.get(current)! + next.weight; const old = distance.get(next.node)!; const improves = candidate < old; if (improves) distance.set(next.node, candidate); steps.push({ id: `dijkstra-${sequence++}`, operation: improves ? "relax-distance" : "keep-distance", explanation: `${current} → ${next.node} offers ${distance.get(current)} + ${next.weight} = ${candidate}. ${improves ? `Update ${next.node} from ${Number.isFinite(old) ? old : "∞"} to ${candidate}.` : `Keep the better known distance ${old}.`}`, codeLine: improves ? 10 : 9, frame: weightedFrame(input, true, [current, next.node], settled, `${next.node}: ${Number.isFinite(old) ? old : "∞"} → ${improves ? candidate : old}`, distanceOutput(input.nodes, distance), [next.edge], [], improves ? [next.node] : [], [], distanceLabels(input.nodes, distance)) }); } }
    steps.push({ id: "dijkstra-complete", operation: "shortest-paths-complete", explanation: "Every reachable vertex is settled with its shortest distance from the start.", codeLine: 12, frame: weightedFrame(input, true, [], settled, `Shortest distances from ${input.start}`, distanceOutput(input.nodes, distance), [], input.edges.map((_, index) => edgeId(index)), [], [], distanceLabels(input.nodes, distance)) }); return steps;
  },
};

export const bellmanFordLesson: LessonDefinition<WeightedGraphInput> = {
  id: "bellman-ford", title: "Bellman–Ford algorithm", category: "algorithm",
  code: ["def bellman_ford(vertices, edges, start):", "    distance = {v: inf for v in vertices}", "    distance[start] = 0", "    for _ in range(len(vertices) - 1):", "        changed = False", "        for u, v, weight in edges:", "            if distance[u] + weight < distance[v]:", "                distance[v] = distance[u] + weight", "                changed = True", "        if not changed: break", "    for u, v, weight in edges:", "        if distance[u] + weight < distance[v]:", "            raise NegativeCycle", "    return distance"],
  validate: (input) => validateWeighted(input, true),
  createSteps: (input) => {
    const distance = new Map(input.nodes.map((node) => [node, Infinity])); distance.set(input.start, 0); const steps: VisualizationStep[] = [{ id: "bellman-0", operation: "initialize", explanation: `Start with distance 0 at ${input.start}. Negative edges are allowed.`, codeLine: 2, frame: weightedFrame(input, true, [input.start], [], "Pass 0 · initialize", distanceOutput(input.nodes, distance), [], [], [input.start], [], distanceLabels(input.nodes, distance)) }]; let sequence = 1;
    for (let pass = 1; pass < input.nodes.length; pass += 1) { let changed = false; steps.push({ id: `bellman-${sequence++}`, operation: "start-pass", explanation: `Pass ${pass} checks every directed edge. After this pass, shortest paths using at most ${pass} edge${pass === 1 ? "" : "s"} are known.`, codeLine: 3, frame: weightedFrame(input, true, [], [], `Relaxation pass ${pass} of ${input.nodes.length - 1}`, distanceOutput(input.nodes, distance), [], [], [], [], distanceLabels(input.nodes, distance)) }); for (let index = 0; index < input.edges.length; index += 1) { const edge = input.edges[index]; const fromDistance = distance.get(edge.from)!; const candidate = fromDistance + edge.weight; const old = distance.get(edge.to)!; const improves = Number.isFinite(fromDistance) && candidate < old; if (improves) { distance.set(edge.to, candidate); changed = true; } steps.push({ id: `bellman-${sequence++}`, operation: improves ? "relax-edge" : "keep-distance", explanation: Number.isFinite(fromDistance) ? `${edge.from} → ${edge.to} offers ${fromDistance} + (${edge.weight}) = ${candidate}. ${improves ? `Update ${edge.to}.` : "No improvement."}` : `${edge.from} is still unreachable, so this edge cannot improve ${edge.to} yet.`, codeLine: improves ? 7 : 6, frame: weightedFrame(input, true, [edge.from, edge.to], [], `Pass ${pass} · ${edge.from} → ${edge.to}`, distanceOutput(input.nodes, distance), [edgeId(index)], [], improves ? [edge.to] : [], [], distanceLabels(input.nodes, distance)) }); } if (!changed) break; }
    const cycleEdge = input.edges.findIndex((edge) => Number.isFinite(distance.get(edge.from)) && distance.get(edge.from)! + edge.weight < distance.get(edge.to)!);
    if (cycleEdge >= 0) { const edge = input.edges[cycleEdge]; steps.push({ id: "bellman-negative-cycle", operation: "negative-cycle-detected", explanation: `${edge.from} → ${edge.to} can still lower a distance after V−1 passes. A reachable negative cycle exists, so shortest distances are undefined.`, codeLine: 12, frame: weightedFrame(input, true, [edge.from, edge.to], [], "Negative cycle detected", ["No finite shortest solution"], [edgeId(cycleEdge)], [], [], [], distanceLabels(input.nodes, distance)) }); }
    else steps.push({ id: "bellman-complete", operation: "shortest-paths-complete", explanation: "No edge can improve any distance. These are the shortest costs, even with negative edges.", codeLine: 13, frame: weightedFrame(input, true, [], input.nodes.filter((node) => Number.isFinite(distance.get(node))), `Shortest distances from ${input.start}`, distanceOutput(input.nodes, distance), [], input.edges.map((_, index) => edgeId(index)), [], [], distanceLabels(input.nodes, distance)) }); return steps;
  },
};

function matrixFrame(input: WeightedGraphInput, distances: number[][], active: [number, number] | null, completed: boolean, caption: string, intermediate?: string) {
  const items: VisualItem[] = input.nodes.flatMap((row, i) => input.nodes.map((column, j) => ({ id: `weighted-matrix-${row}-${column}`, value: Number.isFinite(distances[i][j]) ? distances[i][j] : "∞", label: `${row} → ${column}`, state: active?.[0] === i && active[1] === j ? "active" : completed ? "completed" : i === j ? "muted" : "idle" })));
  return { layout: "matrix" as const, columns: input.nodes.length, items, caption, output: intermediate ? [`via ${intermediate}`] : input.nodes.map((node, index) => `${node}: ${distances[index].map((value) => Number.isFinite(value) ? value : "∞").join(", ")}`) };
}

export const floydWarshallLesson: LessonDefinition<WeightedGraphInput> = {
  id: "floyd-warshall", title: "Floyd–Warshall algorithm", category: "algorithm",
  code: ["def floyd_warshall(distance):", "    for via in range(n):", "        for start in range(n):", "            for end in range(n):", "                candidate = distance[start][via] + distance[via][end]", "                distance[start][end] = min(distance[start][end], candidate)", "    return distance"],
  validate: (input) => validateWeighted(input, true),
  createSteps: (input) => {
    const n = input.nodes.length; const distances = Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => i === j ? 0 : Infinity)); input.edges.forEach((edge) => { const i = input.nodes.indexOf(edge.from); const j = input.nodes.indexOf(edge.to); distances[i][j] = Math.min(distances[i][j], edge.weight); }); const steps: VisualizationStep[] = [{ id: "floyd-0", operation: "initialize-matrix", explanation: "Start with 0 on the diagonal, direct edge weights, and infinity where no direct route exists.", codeLine: 0, frame: matrixFrame(input, distances, null, false, "Direct distances only") }]; let sequence = 1;
    for (let via = 0; via < n; via += 1) { steps.push({ id: `floyd-${sequence++}`, operation: "choose-intermediate", explanation: `Allow ${input.nodes[via]} as an intermediate stop. Compare every start-to-end pair through it.`, codeLine: 1, frame: matrixFrame(input, distances, null, false, `Intermediate vertex: ${input.nodes[via]}`, input.nodes[via]) }); for (let start = 0; start < n; start += 1) for (let end = 0; end < n; end += 1) { const candidate = distances[start][via] + distances[via][end]; if (candidate < distances[start][end]) { const old = distances[start][end]; distances[start][end] = candidate; steps.push({ id: `floyd-${sequence++}`, operation: "improve-pair", explanation: `${input.nodes[start]} → ${input.nodes[via]} → ${input.nodes[end]} costs ${candidate}, improving ${Number.isFinite(old) ? old : "∞"}.`, codeLine: 5, frame: matrixFrame(input, distances, [start, end], false, `${input.nodes[start]} → ${input.nodes[end]} becomes ${candidate}`, input.nodes[via]) }); } } }
    steps.push({ id: "floyd-complete", operation: "all-pairs-complete", explanation: "Every vertex has been considered as an intermediate, so the matrix contains all-pairs shortest distances.", codeLine: 6, frame: matrixFrame(input, distances, null, true, "All-pairs shortest paths") }); return steps;
  },
};

export const primLesson: LessonDefinition<WeightedGraphInput> = {
  id: "prim", title: "Prim's algorithm", category: "algorithm",
  code: ["def prim(graph, start):", "    tree = {start}", "    chosen = []", "    while len(tree) < len(graph):", "        edge = min(crossing_edges(tree), key=weight)", "        chosen.append(edge)", "        tree.add(edge.new_vertex)", "    return chosen"],
  validate: (input) => validateWeighted(input, false, { connected: true }),
  createSteps: (input) => {
    const selected = new Set([input.start]); const chosen: string[] = []; const output: string[] = []; let total = 0; let sequence = 1; const steps: VisualizationStep[] = [{ id: "prim-0", operation: "start-tree", explanation: `Start the growing tree at ${input.start}. No edge has been chosen yet.`, codeLine: 1, frame: weightedFrame(input, false, [input.start], [], `Tree vertices: ${input.start} · cost 0`, [], [], [], [input.start]) }];
    while (selected.size < input.nodes.length) { let bestIndex = -1; input.edges.forEach((edge, index) => { const crossing = selected.has(edge.from) !== selected.has(edge.to); if (crossing && (bestIndex < 0 || edge.weight < input.edges[bestIndex].weight)) bestIndex = index; }); const edge = input.edges[bestIndex]; const next = selected.has(edge.from) ? edge.to : edge.from; steps.push({ id: `prim-${sequence++}`, operation: "choose-lightest-crossing-edge", explanation: `${edge.from} — ${edge.to} is the lightest edge crossing from the current tree to an outside vertex.`, codeLine: 4, frame: weightedFrame(input, false, [edge.from, edge.to], [...selected], `Candidate weight ${edge.weight}`, [...output], [edgeId(bestIndex)], chosen) }); selected.add(next); chosen.push(edgeId(bestIndex)); total += edge.weight; output.push(`${edge.from}-${edge.to}:${edge.weight}`); steps.push({ id: `prim-${sequence++}`, operation: "grow-tree", explanation: `Add ${next} and edge weight ${edge.weight}. Running tree cost is ${total}.`, codeLine: 6, frame: weightedFrame(input, false, [next], [...selected].filter((node) => node !== next), `MST cost: ${total}`, [...output], [], chosen, [next]) }); }
    steps.push({ id: "prim-complete", operation: "mst-complete", explanation: `${input.nodes.length - 1} edges connect every vertex without a cycle. Total minimum cost is ${total}.`, codeLine: 7, frame: weightedFrame(input, false, [], [...selected], `Minimum spanning tree · total ${total}`, [...output, `TOTAL=${total}`], [], chosen, [], input.edges.map((_, index) => edgeId(index)).filter((id) => !chosen.includes(id))) }); return steps;
  },
};

function disjointSet(nodes: string[]) {
  const parent = new Map(nodes.map((node) => [node, node])); const rank = new Map(nodes.map((node) => [node, 0]));
  const find = (node: string): string => { const current = parent.get(node)!; if (current !== node) parent.set(node, find(current)); return parent.get(node)!; };
  const union = (a: string, b: string) => { let rootA = find(a); let rootB = find(b); if (rootA === rootB) return false; if (rank.get(rootA)! < rank.get(rootB)!) [rootA, rootB] = [rootB, rootA]; parent.set(rootB, rootA); if (rank.get(rootA) === rank.get(rootB)) rank.set(rootA, rank.get(rootA)! + 1); return true; };
  return { find, union };
}

export const kruskalLesson: LessonDefinition<WeightedGraphInput> = {
  id: "kruskal", title: "Kruskal's algorithm", category: "algorithm",
  code: ["def kruskal(vertices, edges):", "    sets = DisjointSet(vertices)", "    chosen = []", "    for edge in sorted(edges, key=weight):", "        if sets.find(edge.u) != sets.find(edge.v):", "            sets.union(edge.u, edge.v)", "            chosen.append(edge)", "    return chosen"],
  validate: (input) => validateWeighted(input, false, { connected: true }),
  createSteps: (input) => {
    const sets = disjointSet(input.nodes); const sorted = input.edges.map((edge, index) => ({ edge, index })).sort((a, b) => a.edge.weight - b.edge.weight || a.index - b.index); const chosen: string[] = []; const rejected: string[] = []; const output: string[] = []; let total = 0; const steps: VisualizationStep[] = [{ id: "kruskal-0", operation: "sort-edges", explanation: `Sort all edges by weight: ${sorted.map(({ edge }) => edge.weight).join(", ")}.`, codeLine: 3, frame: weightedFrame(input, false, [], [], "Process lightest edges first", sorted.map(({ edge }) => `${edge.from}-${edge.to}:${edge.weight}`)) }];
    sorted.forEach(({ edge, index }, order) => { const joins = sets.find(edge.from) !== sets.find(edge.to); steps.push({ id: `kruskal-check-${order}`, operation: "check-edge", explanation: `${edge.from} — ${edge.to} has weight ${edge.weight}. Its endpoints are ${joins ? "in different sets" : "already connected"}.`, codeLine: 4, frame: weightedFrame(input, false, [edge.from, edge.to], [], joins ? "Safe: no cycle" : "Reject: would form a cycle", [...output], [edgeId(index)], chosen, [], rejected) }); if (joins) { sets.union(edge.from, edge.to); chosen.push(edgeId(index)); total += edge.weight; output.push(`${edge.from}-${edge.to}:${edge.weight}`); } else rejected.push(edgeId(index)); });
    steps.push({ id: "kruskal-complete", operation: "mst-complete", explanation: `The selected ${chosen.length} edges connect every vertex at minimum total cost ${total}.`, codeLine: 7, frame: weightedFrame(input, false, [], input.nodes, `Minimum spanning tree · total ${total}`, [...output, `TOTAL=${total}`], [], chosen, [], rejected) }); return steps;
  },
};

export const unionFindLesson: LessonDefinition<WeightedGraphInput> = {
  id: "union-find", title: "Union-Find", category: "data-structure",
  code: ["class DisjointSet:", "    def find(self, item):", "        if self.parent[item] != item:", "            self.parent[item] = self.find(self.parent[item])", "        return self.parent[item]", "", "    def union(self, a, b):", "        root_a, root_b = self.find(a), self.find(b)", "        if root_a == root_b: return False", "        merge_by_rank(root_a, root_b)", "        return True"],
  validate: (input) => validateWeighted(input, false),
  createSteps: (input) => {
    const sets = disjointSet(input.nodes); const chosen: string[] = []; const rejected: string[] = []; const steps: VisualizationStep[] = [{ id: "union-0", operation: "make-singletons", explanation: "Initially every vertex is the representative of its own separate set.", codeLine: 0, frame: weightedFrame(input, false, [], [], `${input.nodes.length} separate sets`, input.nodes.map((node) => `{${node}}`), [], [], [], [], Object.fromEntries(input.nodes.map((node) => [node, `SET ${node}`]))) }];
    input.edges.forEach((edge, index) => { const rootA = sets.find(edge.from); const rootB = sets.find(edge.to); const joins = rootA !== rootB; steps.push({ id: `union-find-${index}`, operation: "find-representatives", explanation: `find(${edge.from}) = ${rootA} and find(${edge.to}) = ${rootB}. ${joins ? "Different representatives can be united." : "Matching representatives reveal a cycle."}`, codeLine: joins ? 7 : 8, frame: weightedFrame(input, false, [edge.from, edge.to], [], joins ? "UNION the two sets" : "SAME SET · reject edge", input.nodes.map((node) => `${node}→${sets.find(node)}`), [edgeId(index)], chosen, [], rejected, Object.fromEntries(input.nodes.map((node) => [node, `SET ${sets.find(node)}`]))) }); if (joins) { sets.union(edge.from, edge.to); chosen.push(edgeId(index)); } else rejected.push(edgeId(index)); });
    steps.push({ id: "union-complete", operation: "sets-complete", explanation: "Union joins components quickly; Find answers whether two vertices already share a component.", codeLine: 10, frame: weightedFrame(input, false, [], input.nodes, `${new Set(input.nodes.map((node) => sets.find(node))).size} set${new Set(input.nodes.map((node) => sets.find(node))).size === 1 ? "" : "s"} remain`, input.nodes.map((node) => `${node}→${sets.find(node)}`), [], chosen, [], rejected, Object.fromEntries(input.nodes.map((node) => [node, `SET ${sets.find(node)}`]))) }); return steps;
  },
};

const usage = (summary: string, examples: string[], chooseWhen: string, avoidWhen: string, operations: [string, string][], practice: string): UsageGuide => ({ summary, examples, chooseWhen, avoidWhen, operations: operations.map(([name, cost]) => ({ name, cost })), practice });

export const weightedGraphMeta: Record<WeightedGraphLessonId, WeightedGraphMeta> = {
  "weighted-basics": { id: "weighted-basics", navLabel: "Weights & Cost", shortLabel: "w", title: "Weights, Paths & Relaxation", description: "See how edge costs change what “best path” means and how relaxation improves a tentative answer.", concept: "A path's cost is the sum of its edge weights.", rule: "relax when candidate < known", analogy: "choosing roads by travel time, not road count", usage: usage("Weighted graphs model connections whose costs are not all equal.", ["Travel time", "Network latency", "Shipping cost"], "Edges carry meaningful distance, time, price, or risk.", "Every connection has equal cost; unweighted BFS may be simpler.", [["Path cost", "sum(weights)"], ["Storage", "O(V+E)"], ["Relax", "O(1)"]], "Compare a two-edge cheap path with a one-edge expensive path.") },
  dijkstra: { id: "dijkstra", navLabel: "Dijkstra", shortLabel: "D", title: "Dijkstra's Shortest Paths", description: "Settle the nearest tentative vertex and relax its outgoing edges using a priority queue.", concept: "The smallest unsettled distance becomes permanent.", rule: "non-negative weights only", analogy: "expanding a travel-time boundary", usage: usage("Dijkstra efficiently finds shortest paths from one source when all weights are non-negative.", ["GPS routing", "Network routing", "Game navigation"], "Weights are non-negative and single-source shortest paths are needed.", "Any reachable edge can be negative.", [["Heap time", "O((V+E)log V)"], ["Space", "O(V+E)"], ["Source", "single"]], "Store parents and reconstruct the shortest route to one target.") },
  "bellman-ford": { id: "bellman-ford", navLabel: "Bellman–Ford", shortLabel: "BF", title: "Bellman–Ford Shortest Paths", description: "Relax every directed edge repeatedly and detect reachable negative-cost cycles.", concept: "A shortest simple path uses at most V−1 edges.", rule: "negative edges allowed", analogy: "rechecking every fare after each discount", usage: usage("Bellman–Ford handles negative weights and reports when a shortest solution cannot exist.", ["Currency arbitrage", "Constraint systems", "Negative adjustments"], "Negative edges or negative-cycle detection are required.", "All weights are non-negative and faster Dijkstra is available.", [["Time", "O(VE)"], ["Space", "O(V)"], ["Passes", "V−1"]], "Add one reachable negative cycle and watch the extra pass detect it.") },
  "floyd-warshall": { id: "floyd-warshall", navLabel: "Floyd–Warshall", shortLabel: "FW", title: "Floyd–Warshall All-Pairs", description: "Improve every start-to-end distance by allowing one more intermediate vertex at a time.", concept: "Compare direct cost with start → via → end.", rule: "all pairs · dynamic programming", analogy: "updating a complete travel-time table", usage: usage("Floyd–Warshall computes shortest distances between every pair in a small dense graph.", ["Network reachability", "City distance tables", "Transitive closure"], "You need all-pairs answers and the vertex count is moderate.", "The graph is very large and sparse or only one source matters.", [["Time", "O(V³)"], ["Space", "O(V²)"], ["Sources", "all"]], "Explain what distances are valid after intermediate k.") },
  prim: { id: "prim", navLabel: "Prim MST", shortLabel: "P", title: "Prim's Minimum Spanning Tree", description: "Grow one connected tree by repeatedly choosing the lightest edge that reaches a new vertex.", concept: "Choose the cheapest edge crossing the current tree boundary.", rule: "connected undirected graph", analogy: "extending one low-cost cable network", usage: usage("Prim builds a minimum-cost connection network from one growing region.", ["Fiber networks", "Road planning", "Circuit wiring"], "The graph is connected, weighted, and often dense.", "You need shortest routes from a source rather than minimum total network cost.", [["Heap time", "O(E log V)"], ["Edges chosen", "V−1"], ["Space", "O(V+E)"]], "Explain why the chosen edge must cross the tree boundary.") },
  kruskal: { id: "kruskal", navLabel: "Kruskal MST", shortLabel: "K", title: "Kruskal's Minimum Spanning Tree", description: "Process edges from lightest to heaviest, accepting only edges that join different components.", concept: "Cheap edges are safe unless they create a cycle.", rule: "sort edges + Union-Find", analogy: "merging islands with the cheapest bridges", usage: usage("Kruskal is a natural MST choice for sparse graphs and edge-list data.", ["Utility networks", "Clustering", "Image segmentation"], "Edges are easy to sort and the graph is sparse.", "The graph is dense and already stored by vertex neighbors.", [["Time", "O(E log E)"], ["Union-Find", "near O(1)"], ["Edges chosen", "V−1"]], "Mark which sorted edge is the first rejected cycle.") },
  "union-find": { id: "union-find", navLabel: "Union-Find", shortLabel: "UF", title: "Union-Find Sets", description: "Track changing components with Find representatives and Union merges.", concept: "Two items are connected when their representatives match.", rule: "path compression + rank", analogy: "clubs identified by one group captain", usage: usage("Union-Find answers repeated connectivity questions while groups are merged.", ["Kruskal cycle checks", "Dynamic connectivity", "Account merging"], "Connections are only added and component membership is queried often.", "Connections must be removed or full paths are needed.", [["Find", "O(α(n))*"], ["Union", "O(α(n))*"], ["Space", "O(n)"]], "Trace how path compression shortens parent chains.") },
};
