"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { curriculumModules } from "@/lib/curriculum.ts";
import { parsePracticeProgress, practiceQuestions, practiceSummary, recordPracticeAnswer, type PracticeProgress } from "@/lib/practice.ts";
import { CourseMenu } from "./course-menu";
import { ProgressBadge } from "./progress-badge";
import { readLocalValue, writeLocalValue } from "@/lib/local-progress.ts";

type PracticeFilter = "all" | string;
const practiceStorageKey = "algolab-practice-progress";

export function PracticeLab() {
  const [filter, setFilter] = useState<PracticeFilter>("all");
  const [questionId, setQuestionId] = useState(practiceQuestions[0].id);
  const [selectedAnswer, setSelectedAnswer] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [showHint, setShowHint] = useState(false);
  const [progress, setProgress] = useState<PracticeProgress>({});

  useEffect(() => { const stored = parsePracticeProgress(readLocalValue(practiceStorageKey)); queueMicrotask(() => setProgress(stored)); }, []);

  const summary = useMemo(() => practiceSummary(progress), [progress]);
  const filteredQuestions = useMemo(() => filter === "all" ? practiceQuestions : practiceQuestions.filter((question) => question.moduleId === filter), [filter]);
  const current = filteredQuestions.find((question) => question.id === questionId) ?? filteredQuestions[0];
  const currentIndex = filteredQuestions.findIndex((question) => question.id === current.id);
  const currentModule = curriculumModules.find((module) => module.id === current.moduleId)!;
  const answerCorrect = selectedAnswer === current.answer;
  const mastered = progress[current.id]?.mastered ?? false;

  const resetQuestionState = () => { setSelectedAnswer(""); setSubmitted(false); setShowHint(false); };
  const chooseFilter = (next: PracticeFilter) => { const nextQuestions = next === "all" ? practiceQuestions : practiceQuestions.filter((question) => question.moduleId === next); setFilter(next); setQuestionId(nextQuestions.find((question) => !progress[question.id]?.mastered)?.id ?? nextQuestions[0].id); resetQuestionState(); };
  const submitAnswer = () => { if (!selectedAnswer || submitted) return; const next = recordPracticeAnswer(progress, current.id, answerCorrect); setProgress(next); setSubmitted(true); writeLocalValue(practiceStorageKey, JSON.stringify(next)); };
  const nextQuestion = () => { const later = filteredQuestions.slice(currentIndex + 1); const earlier = filteredQuestions.slice(0, currentIndex + 1); const next = [...later, ...earlier].find((question) => !progress[question.id]?.mastered) ?? filteredQuestions[(currentIndex + 1) % filteredQuestions.length]; setQuestionId(next.id); resetQuestionState(); };

  return <main className="app-shell practice-shell"><aside className="sidebar curriculum-sidebar practice-sidebar"><div className="brand"><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span><strong>AlgoLab</strong><small>Learn by seeing</small></span></div><div className="checkpoint-progress practice-side-progress"><div><span>Question mastery</span><strong>{summary.masteredQuestions} / {practiceQuestions.length}</strong></div><div className="progress-track"><span style={{ width: `${summary.masteredQuestions / practiceQuestions.length * 100}%` }} /></div><small>{summary.accuracy}% accuracy across {summary.attempts} attempt{summary.attempts === 1 ? "" : "s"}</small></div><nav aria-label="Practice modules"><p>Course overview</p><Link className="nav-section-link" href="/curriculum"><span>←</span><b>Course map</b></Link><p>Practice filters</p><button className={`nav-item ${filter === "all" ? "active" : ""}`} onClick={() => chooseFilter("all")}><span>★</span><b>All modules</b><i>{summary.masteredQuestions}/{practiceQuestions.length}</i></button>{curriculumModules.map((module) => { const moduleProgress = summary.modules[module.id]; return <button className={`nav-item ${filter === module.id ? "active" : ""}`} onClick={() => chooseFilter(module.id)} key={module.id}><span>{module.checkpoint}</span><b>{module.title}</b><i>{moduleProgress.mastered}/{moduleProgress.total}</i></button>; })}</nav><div className="sidebar-tip"><span>✦</span><p><strong>Retry is part of learning</strong><small>A question stays mastered after a correct answer, even when you revisit it.</small></p></div></aside>
    <section className="workspace"><header className="topbar"><div><span>Checkpoint 12</span><b>/</b><strong>Practice Lab</strong></div><div className="topbar-actions"><CourseMenu currentPath="/practice" /><ProgressBadge label="Results saved locally" /></div></header><div className="page-content practice-content">
      <label className="mobile-lesson-select">Practice module<select value={filter} onChange={(event) => chooseFilter(event.target.value)}><option value="all">All modules</option>{curriculumModules.map((module) => <option value={module.id} key={module.id}>{module.title}</option>)}</select></label>
      <section className="practice-heading"><div><span className="eyebrow">RECALL · ANSWER · EXPLAIN · REVIEW</span><h1>Check what you understand—not only what you recognize.</h1><p>Use short questions to retrieve the idea from memory. Every answer explains the reasoning and links back to the interactive lesson when you need another look.</p></div><div className="practice-heading-score"><strong>{summary.accuracy}%</strong><span>attempt accuracy</span></div></section>
      <section className="practice-stats" aria-label="Practice progress"><div><span>Mastered questions</span><strong>{summary.masteredQuestions}<small> / {practiceQuestions.length}</small></strong></div><div><span>Modules mastered</span><strong>{summary.masteredModules}<small> / {curriculumModules.length}</small></strong></div><div><span>Total attempts</span><strong>{summary.attempts}</strong></div><div><span>Questions attempted</span><strong>{summary.attemptedQuestions}<small> / {practiceQuestions.length}</small></strong></div></section>
      <section className="practice-workspace"><article className="practice-question-card"><header><div><span>QUESTION {currentIndex + 1} OF {filteredQuestions.length}</span><strong>{currentModule.title} · {current.topic}</strong></div><span className={mastered ? "mastered" : "unmastered"}>{mastered ? "Mastered ✓" : "Practice"}</span></header><div className="practice-question-body"><h2>{current.prompt}</h2><div className="practice-options" role="radiogroup" aria-label="Answer choices">{current.options.map((option) => { const correctOption = submitted && option.id === current.answer; const incorrectChoice = submitted && option.id === selectedAnswer && !answerCorrect; return <button type="button" role="radio" aria-checked={selectedAnswer === option.id} disabled={submitted} className={`${selectedAnswer === option.id ? "selected" : ""} ${correctOption ? "correct" : ""} ${incorrectChoice ? "incorrect" : ""}`} onClick={() => setSelectedAnswer(option.id)} key={option.id}><span>{option.id.toUpperCase()}</span><strong>{option.label}</strong>{correctOption && <i>✓</i>}{incorrectChoice && <i>×</i>}</button>; })}</div>{!submitted && <div className="practice-hint"><button type="button" onClick={() => setShowHint((visible) => !visible)}>{showHint ? "Hide hint" : "Need a hint?"}</button>{showHint && <p>{current.hint}</p>}</div>}{submitted && <div className={`practice-feedback ${answerCorrect ? "correct" : "incorrect"}`} role="status"><span>{answerCorrect ? "✓" : "!"}</span><div><strong>{answerCorrect ? "Correct—nice reasoning." : `Not yet. The answer is ${current.answer.toUpperCase()}.`}</strong><p>{current.explanation}</p><Link href={current.reviewHref}>Review the visual lesson <span>→</span></Link></div></div>}</div><footer><div><span>Progress in this filter</span><div><i style={{ width: `${filteredQuestions.filter((question) => progress[question.id]?.mastered).length / filteredQuestions.length * 100}%` }} /></div></div>{submitted ? <button type="button" className="practice-primary" onClick={nextQuestion}>Next question <span>→</span></button> : <button type="button" className="practice-primary" onClick={submitAnswer} disabled={!selectedAnswer}>Check answer</button>}</footer></article>
        <aside className="practice-module-panel"><div className="practice-panel-heading"><span>MODULE MASTERY</span><strong>{filter === "all" ? "All curriculum areas" : currentModule.title}</strong></div><div className="practice-module-list">{curriculumModules.filter((module) => filter === "all" || module.id === filter).map((module) => { const moduleProgress = summary.modules[module.id]; return <button type="button" onClick={() => chooseFilter(module.id)} key={module.id}><span>{module.checkpoint}</span><div><strong>{module.title}</strong><small>{moduleProgress.mastered} of {moduleProgress.total} mastered</small><i><b style={{ width: `${moduleProgress.mastered / moduleProgress.total * 100}%` }} /></i></div>{moduleProgress.mastered === moduleProgress.total ? <em>✓</em> : <em>→</em>}</button>; })}</div><Link href="/curriculum">View the complete course map <span>→</span></Link></aside>
      </section>
      <section className="practice-method"><div className="curriculum-section-heading"><span>A SIMPLE STUDY LOOP</span><h2>Turn visual understanding into recall</h2></div><div><article><span>1</span><strong>Predict</strong><p>Choose an answer before revealing any explanation.</p></article><article><span>2</span><strong>Explain</strong><p>Say why the right option works and why another one fails.</p></article><article><span>3</span><strong>Review</strong><p>Return to the visual lesson when the rule still feels uncertain.</p></article><article><span>4</span><strong>Retry</strong><p>Come back later and answer without relying on recognition.</p></article></div></section>
    </div></section></main>;
}
