"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import {
  bellmanFordLesson,
  dijkstraLesson,
  floydWarshallLesson,
  kruskalLesson,
  primLesson,
  unionFindLesson,
  weightedBasicsLesson,
  weightedGraphMeta,
  type WeightedEdgeInput,
  type WeightedGraphLessonId,
} from "@/lib/lessons/index.ts";
import { createTimeline } from "@/lib/visualization/index.ts";
import type { VisualizationStep, VisualEdge } from "@/lib/visualization/types.ts";
import { useVisualizationPlayer } from "./use-visualization-player";

const lessonOrder: WeightedGraphLessonId[] = ["weighted-basics", "dijkstra", "bellman-ford", "floyd-warshall", "prim", "kruskal", "union-find"];
const definitions = { "weighted-basics": weightedBasicsLesson, dijkstra: dijkstraLesson, "bellman-ford": bellmanFordLesson, "floyd-warshall": floydWarshallLesson, prim: primLesson, kruskal: kruskalLesson, "union-find": unionFindLesson } as const;
const positions = [{ x: 50, y: 12 }, { x: 21, y: 35 }, { x: 79, y: 35 }, { x: 14, y: 76 }, { x: 50, y: 68 }, { x: 86, y: 76 }, { x: 50, y: 91 }];
const positiveEdges: WeightedEdgeInput[] = [{ from: "A", to: "B", weight: 4 }, { from: "A", to: "C", weight: 2 }, { from: "C", to: "B", weight: 1 }, { from: "B", to: "D", weight: 5 }, { from: "C", to: "D", weight: 8 }, { from: "C", to: "E", weight: 10 }, { from: "D", to: "E", weight: 2 }, { from: "D", to: "F", weight: 6 }, { from: "E", to: "F", weight: 3 }];
const bellmanEdges: WeightedEdgeInput[] = [{ from: "A", to: "B", weight: 4 }, { from: "A", to: "C", weight: 5 }, { from: "B", to: "C", weight: -2 }, { from: "B", to: "D", weight: 4 }, { from: "C", to: "D", weight: 3 }, { from: "D", to: "E", weight: 2 }, { from: "C", to: "E", weight: 6 }];
const floydEdges: WeightedEdgeInput[] = [{ from: "A", to: "B", weight: 3 }, { from: "A", to: "D", weight: 7 }, { from: "B", to: "A", weight: 8 }, { from: "B", to: "C", weight: 2 }, { from: "C", to: "A", weight: 5 }, { from: "C", to: "D", weight: 1 }, { from: "D", to: "A", weight: 2 }];

function presetFor(lessonId: WeightedGraphLessonId) {
  if (lessonId === "bellman-ford") return { nodes: ["A", "B", "C", "D", "E"], edges: bellmanEdges.map((edge) => ({ ...edge })), start: "A" };
  if (lessonId === "floyd-warshall") return { nodes: ["A", "B", "C", "D"], edges: floydEdges.map((edge) => ({ ...edge })), start: "A" };
  return { nodes: ["A", "B", "C", "D", "E", "F"], edges: positiveEdges.map((edge) => ({ ...edge })), start: "A" };
}
function edgeText(edges: WeightedEdgeInput[]) { return edges.map((edge) => `${edge.from}-${edge.to}:${edge.weight}`).join(", "); }

function edgeGeometry(edge: VisualEdge, step: VisualizationStep) {
  const fromIndex = step.frame.items.findIndex((item) => item.id === edge.from); const toIndex = step.frame.items.findIndex((item) => item.id === edge.to); const from = positions[fromIndex]; const to = positions[toIndex]; const dx = to.x - from.x; const dy = (to.y - from.y) * (9 / 16); const width = Math.sqrt(dx * dx + dy * dy); const angle = Math.atan2(dy, dx) * 180 / Math.PI;
  return { line: { left: `${from.x}%`, top: `${from.y}%`, width: `${width}%`, transform: `rotate(${angle}deg)` }, badge: { left: `${(from.x + to.x) / 2}%`, top: `${(from.y + to.y) / 2}%` } };
}

function WeightedGraphCanvas({ step }: { step: VisualizationStep }) {
  return <div className="graph-canvas weighted-graph-canvas">{step.frame.edges?.map((edge) => { const geometry = edgeGeometry(edge, step); return <span className="weighted-edge-wrap" key={edge.id}><i className={`graph-edge state-${edge.state} ${edge.directed ? "directed" : ""}`} style={geometry.line} /><b className={`weight-badge state-${edge.state}`} style={geometry.badge}>{edge.label}</b></span>; })}{step.frame.items.map((item, index) => <div className={`graph-node weighted-graph-node state-${item.state}`} style={{ left: `${positions[index].x}%`, top: `${positions[index].y}%` }} key={item.id}><small>{item.label}</small><strong>{item.value}</strong></div>)}</div>;
}

function WeightedMatrixStage({ step }: { step: VisualizationStep }) {
  return <div className="graph-matrix-stage weighted-matrix-stage"><div className="structure-caption">{step.frame.caption}</div><div className="graph-matrix" style={{ gridTemplateColumns: `repeat(${step.frame.columns ?? 3}, minmax(38px, 1fr))` }}>{step.frame.items.map((item) => <div className={`graph-matrix-cell state-${item.state}`} key={item.id}><small>{item.label}</small><strong>{item.value}</strong></div>)}</div><div className="traversal-output weighted-matrix-output"><small>DISTANCE TABLE / INTERMEDIATE</small><div>{step.frame.output?.map((value, index) => <span key={`${value}-${index}`}>{value}</span>)}</div></div></div>;
}

function WeightedStage({ step }: { step: VisualizationStep }) {
  if (step.frame.layout === "matrix") return <WeightedMatrixStage step={step} />;
  return <div className="graph-stage weighted-stage"><div className="structure-caption">{step.frame.caption}</div><WeightedGraphCanvas step={step} /><div className="traversal-output graph-output weighted-output"><small>DISTANCES / SELECTED EDGES / SETS</small><div>{step.frame.output?.length ? step.frame.output.map((value, index) => <span key={`${value}-${index}`}>{value}</span>) : <em>Costs and selected edges appear here as the algorithm runs</em>}</div></div><div className="visual-legend"><span><i className="legend-active" />considering</span><span><i className="legend-completed" />settled / chosen</span><span><i className="legend-idle" />available</span></div></div>;
}

function UsageSection({ lessonId }: { lessonId: WeightedGraphLessonId }) {
  const usage = weightedGraphMeta[lessonId].usage;
  return <section className="usage-section" aria-label={`${weightedGraphMeta[lessonId].title} usage guide`}><div className="usage-heading"><span>USE IT WITH CONFIDENCE</span><h2>Where this weighted algorithm is useful</h2><p>{usage.summary}</p></div><div className="usage-grid"><div className="usage-card choose-card"><span className="usage-icon">✓</span><div><small>Choose it when</small><p>{usage.chooseWhen}</p></div></div><div className="usage-card avoid-card"><span className="usage-icon">!</span><div><small>Think twice when</small><p>{usage.avoidWhen}</p></div></div><div className="usage-card examples-card"><small>Real examples</small><ul>{usage.examples.map((example) => <li key={example}><span>↳</span>{example}</li>)}</ul></div><div className="usage-card complexity-card"><small>Cost guide</small><div>{usage.operations.map((operation) => <p key={operation.name}><span>{operation.name}</span><strong>{operation.cost}</strong></p>)}</div></div></div><div className="practice-strip"><span>Practice next</span><strong>{usage.practice}</strong><button type="button" onClick={() => document.querySelector(".lesson-toolbar")?.scrollIntoView({ behavior: "smooth" })}>Edit the weights ↑</button></div></section>;
}

export function WeightedGraphsLab() {
  const initial = presetFor("weighted-basics"); const [lessonId, setLessonId] = useState<WeightedGraphLessonId>("weighted-basics"); const [nodes, setNodes] = useState(initial.nodes); const [edges, setEdges] = useState(initial.edges); const [start, setStart] = useState(initial.start); const [nodesDraft, setNodesDraft] = useState(initial.nodes.join(", ")); const [edgesDraft, setEdgesDraft] = useState(edgeText(initial.edges)); const [inputError, setInputError] = useState(""); const [completed, setCompleted] = useState<WeightedGraphLessonId[]>([]);
  const directed = ["dijkstra", "bellman-ford", "floyd-warshall"].includes(lessonId); const needsStart = ["weighted-basics", "dijkstra", "bellman-ford", "prim"].includes(lessonId);
  const demo = useMemo(() => { const input = { nodes, edges, start }; if (lessonId === "weighted-basics") return createTimeline(weightedBasicsLesson, input); if (lessonId === "dijkstra") return createTimeline(dijkstraLesson, input); if (lessonId === "bellman-ford") return createTimeline(bellmanFordLesson, input); if (lessonId === "floyd-warshall") return createTimeline(floydWarshallLesson, input); if (lessonId === "prim") return createTimeline(primLesson, input); if (lessonId === "kruskal") return createTimeline(kruskalLesson, input); return createTimeline(unionFindLesson, input); }, [edges, lessonId, nodes, start]);
  const player = useVisualizationPlayer(demo); const meta = weightedGraphMeta[lessonId]; const step = player.currentStep; const definition = definitions[lessonId];
  useEffect(() => { const stored = window.localStorage.getItem("algolab-weighted-progress"); if (!stored) return; try { const parsed = JSON.parse(stored) as WeightedGraphLessonId[]; queueMicrotask(() => setCompleted(parsed.filter((id) => lessonOrder.includes(id)))); } catch { window.localStorage.removeItem("algolab-weighted-progress"); } }, []);
  useEffect(() => { if (player.state.status !== "completed") return; queueMicrotask(() => setCompleted((previous) => { if (previous.includes(lessonId)) return previous; const next = [...previous, lessonId]; window.localStorage.setItem("algolab-weighted-progress", JSON.stringify(next)); return next; })); }, [lessonId, player.state.status]);
  useEffect(() => { const handleKeyboard = (event: KeyboardEvent) => { const element = event.target as HTMLElement | null; if (["INPUT", "BUTTON", "SELECT"].includes(element?.tagName ?? "")) return; if (event.code === "Space") { event.preventDefault(); if (player.state.status === "playing") player.pause(); else player.play(); } if (event.key === "ArrowRight") player.next(); if (event.key === "ArrowLeft") player.previous(); if (event.key.toLowerCase() === "r") player.reset(); }; window.addEventListener("keydown", handleKeyboard); return () => window.removeEventListener("keydown", handleKeyboard); }, [player]);
  const selectLesson = (next: WeightedGraphLessonId) => { const preset = presetFor(next); player.reset(); setLessonId(next); setNodes(preset.nodes); setEdges(preset.edges); setStart(preset.start); setNodesDraft(preset.nodes.join(", ")); setEdgesDraft(edgeText(preset.edges)); setInputError(""); };
  const applyInput = () => {
    const parsedNodes = nodesDraft.split(",").map((node) => node.trim().toUpperCase()).filter(Boolean); const parsedEdges: WeightedEdgeInput[] = [];
    for (const raw of edgesDraft.split(",").map((edge) => edge.trim()).filter(Boolean)) { const match = raw.toUpperCase().match(/^([A-Z0-9]{1,3})\s*[-→>]\s*([A-Z0-9]{1,3})\s*:\s*(-?\d+)$/); if (!match) { setInputError("Write weighted edges like A-B:4, A-C:2."); return; } parsedEdges.push({ from: match[1], to: match[2], weight: Number(match[3]) }); }
    const nextStart = parsedNodes.includes(start) ? start : parsedNodes[0]; const validation = definition.validate({ nodes: parsedNodes, edges: parsedEdges, start: nextStart }); if (!validation.valid) { setInputError(validation.message); return; }
    player.reset(); setNodes(parsedNodes); setEdges(parsedEdges); setStart(nextStart); setNodesDraft(parsedNodes.join(", ")); setEdgesDraft(edgeText(parsedEdges)); setInputError("");
  };
  const resetExample = () => { const preset = presetFor(lessonId); player.reset(); setNodes(preset.nodes); setEdges(preset.edges); setStart(preset.start); setNodesDraft(preset.nodes.join(", ")); setEdgesDraft(edgeText(preset.edges)); setInputError(""); };
  const nextLesson = () => selectLesson(lessonOrder[(lessonOrder.indexOf(lessonId) + 1) % lessonOrder.length]);

  return <main className="app-shell"><aside className="sidebar linear-sidebar graph-sidebar"><div className="brand"><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span><strong>AlgoLab</strong><small>Learn by seeing</small></span></div><div className="checkpoint-progress"><div><span>Weighted graphs</span><strong>{completed.length} / 7</strong></div><div className="progress-track"><span style={{ width: `${completed.length * (100 / 7)}%` }} /></div></div><nav aria-label="Weighted graph lessons"><p>Previous checkpoint</p><Link className="nav-section-link" href="/graph-foundations"><span>✓</span><b>Graph foundations</b></Link><p>Weighted graphs</p>{lessonOrder.map((id, index) => <button className={`nav-item ${lessonId === id ? "active" : ""}`} onClick={() => selectLesson(id)} key={id}><span>{weightedGraphMeta[id].shortLabel}</span><b>{weightedGraphMeta[id].navLabel}</b><i>{completed.includes(id) ? "✓" : String(index + 1).padStart(2, "0")}</i></button>)}<p>Coming next</p><div className="nav-item locked"><span>10</span><b>Algorithmic techniques</b><i>locked</i></div></nav><div className="sidebar-tip"><span>✦</span><p><strong>Follow the cost</strong><small>Orange compares a candidate. Lime means a distance or tree edge has been accepted.</small></p></div></aside>
    <section className="workspace"><header className="topbar"><div><span>Checkpoint 9</span><b>/</b><strong>Weighted graphs</strong></div><span className="local-badge"><i />Progress saved locally</span></header><div className="page-content linear-content"><label className="mobile-lesson-select">Choose lesson<select value={lessonId} onChange={(event) => selectLesson(event.target.value as WeightedGraphLessonId)}>{lessonOrder.map((id) => <option value={id} key={id}>{weightedGraphMeta[id].navLabel}</option>)}</select></label>
      <section className="page-heading foundation-heading"><div><span className="eyebrow">WEIGHTED LESSON {lessonOrder.indexOf(lessonId) + 1} OF 7 · COMPARE THE COSTS</span><h1>{meta.title}</h1><p>{meta.description}</p></div><div className="shortcut-hint"><span>⌨</span><p><strong>Keyboard controls</strong><small>Space · ← → · R</small></p></div></section><section className="concept-strip"><div className="analogy-mark">{meta.shortLabel}</div><div><small>Start with a familiar picture · {meta.analogy}</small><strong>{meta.concept}</strong></div><span>{meta.rule}</span></section>
      <section className="lesson-toolbar graph-toolbar weighted-toolbar"><div className="graph-inputs weighted-inputs"><label>Vertices<input type="text" value={nodesDraft} onChange={(event) => setNodesDraft(event.target.value)} aria-invalid={Boolean(inputError)} /></label><label>{directed ? "Directed weighted edges" : "Undirected weighted edges"}<input type="text" value={edgesDraft} onChange={(event) => setEdgesDraft(event.target.value)} onKeyDown={(event) => event.key === "Enter" && applyInput()} aria-invalid={Boolean(inputError)} /></label>{needsStart && <label>Start<select value={start} onChange={(event) => { player.reset(); setStart(event.target.value); }}>{nodes.map((node) => <option value={node} key={node}>{node}</option>)}</select></label>}<button type="button" onClick={applyInput}>Apply</button><button type="button" className="secondary-action" onClick={resetExample}>Reset example</button></div><div className="lesson-status"><span className={`status-dot status-${player.state.status}`} />{player.state.status === "idle" ? "Ready to explore" : player.state.status}</div><div className="input-feedback"><span>{directed ? "A-B:4 means A → B costs 4." : "A-B:4 creates a two-way edge costing 4."}</span>{inputError && <strong role="alert">{inputError}</strong>}</div></section>
      <section className="learning-grid foundation-learning-grid"><article className="visual-card"><div className="card-header"><div><span className="live-dot" /><strong>Weighted graph playground</strong></div><span>Step {player.state.index < 0 ? 0 : player.state.index + 1} / {demo.steps.length}</span></div><div className="visual-stage graph-visual-stage weighted-visual-stage"><WeightedStage step={step} /></div><div className="explanation-row"><span>i</span><p><small>What’s happening</small><strong>{step.explanation}</strong></p></div><div className="playback-controls"><button onClick={player.reset} aria-label="Reset visualization">↺</button><button onClick={player.previous} disabled={player.state.index < 0} aria-label="Previous step">‹</button><button className="play-button" onClick={player.state.status === "playing" ? player.pause : player.play} aria-label={player.state.status === "playing" ? "Pause" : "Play"}>{player.state.status === "playing" ? "Ⅱ" : "▶"}</button><button onClick={player.next} disabled={player.state.status === "completed"} aria-label="Next step">›</button><label className="speed-control"><span>Speed <b>{player.state.speed}×</b></span><input type="range" min="1" max="5" value={player.state.speed} onChange={(event) => player.setSpeed(Number(event.target.value))} /></label></div><div className="timeline-progress"><span style={{ width: `${Math.max(0, ((player.state.index + 1) / demo.steps.length) * 100)}%` }} /></div></article>
        <aside className="code-card foundation-code-card"><div className="card-header"><div><span className="python-dot">Py</span><strong>Python</strong></div><span>Follows each step</span></div><div className="code-lines">{definition.code.map((line, index) => <div className={index === step.codeLine ? "code-line active" : "code-line"} key={`${index}-${line}`}><span>{index + 1}</span><code>{line || " "}</code></div>)}</div><div className="event-readout"><span>Current action</span><strong>{step.operation.replaceAll("-", " ")}</strong><small>{step.frame.caption}</small></div></aside></section>
      <UsageSection lessonId={lessonId} /><section className="next-lesson-strip"><div><small>Checkpoint progress</small><strong>{completed.includes(lessonId) ? "Lesson explored ✓" : "Complete the steps to mark this lesson explored"}</strong></div><button onClick={nextLesson}>Next weighted lesson <span>→</span></button></section></div></section></main>;
}
